/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.4
    2025 08 10 16:19:55
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module timer (int_o, htrans_i, hsel_i, hwrite_i, haddr_i, hwdata_i, hready_i,
    hburst_i, hsize_i, hrdata_o, hresp_o, hready_o, clk_i, resetn_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    output  int_o;
    input  [1:0]  htrans_i;
    input  hsel_i;
    input  hwrite_i;
    input  [31:0]  haddr_i;
    input  [31:0]  hwdata_i;
    input  hready_i;
    input  [2:0]  hburst_i;
    input  [2:0]  hsize_i;
    output  [31:0]  hrdata_o;
    output  hresp_o;
    output  hready_o;
    input  clk_i;
    input  resetn_i;
endmodule