    timer __(.int_o( ),
        .htrans_i( ),
        .hsel_i( ),
        .hwrite_i( ),
        .haddr_i( ),
        .hwdata_i( ),
        .hready_i( ),
        .hburst_i( ),
        .hsize_i( ),
        .hrdata_o( ),
        .hresp_o( ),
        .hready_o( ),
        .clk_i( ),
        .resetn_i( ),
        .systime_o( ));
