// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR 
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE. 
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

/* synthesis translate_off*/
`define SBP_SIMULATION
/* synthesis translate_on*/
`ifndef SBP_SIMULATION
`define SBP_SYNTHESIS
`endif



//
// Verific Verilog Description of module ice40_nano
//
module ice40_nano (gpio0_io, clk_i, rstn_i, uart_rxd_00_i, uart_txd_00_o);
    inout [7:0]gpio0_io;
    input clk_i;
    input rstn_i;
    input uart_rxd_00_i;
    output uart_txd_00_o;
    
    wire [31:0]ahbl0_inst_AHBL_M00_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M00_interconnect_HBURST;
    wire [3:0]ahbl0_inst_AHBL_M00_interconnect_HPROT;
    wire [31:0]ahbl0_inst_AHBL_M00_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M00_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M00_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M00_interconnect_HWDATA;
    wire [31:0]ahbl0_inst_AHBL_M01_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M01_interconnect_HBURST;
    wire [31:0]ahbl0_inst_AHBL_M01_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M01_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M01_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M01_interconnect_HWDATA;
    wire [31:0]ahbl0_inst_AHBL_M02_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M02_interconnect_HBURST;
    wire [3:0]ahbl0_inst_AHBL_M02_interconnect_HPROT;
    wire [31:0]ahbl0_inst_AHBL_M02_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M02_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M02_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M02_interconnect_HWDATA;
    wire [31:0]cpu0_inst_AHBL_M1_DATA_interconnect_HADDR;
    wire [2:0]cpu0_inst_AHBL_M1_DATA_interconnect_HBURST;
    wire [3:0]cpu0_inst_AHBL_M1_DATA_interconnect_HPROT;
    wire [31:0]cpu0_inst_AHBL_M1_DATA_interconnect_HRDATA;
    wire [2:0]cpu0_inst_AHBL_M1_DATA_interconnect_HSIZE;
    wire [1:0]cpu0_inst_AHBL_M1_DATA_interconnect_HTRANS;
    wire [31:0]cpu0_inst_AHBL_M1_DATA_interconnect_HWDATA;
    
    wire cpu0_inst_system_resetn_o_net, ahbl0_inst_AHBL_M00_interconnect_HMASTLOCK, 
        ahbl0_inst_AHBL_M00_interconnect_HREADYOUT, ahbl0_inst_AHBL_M00_interconnect_HREADY, 
        ahbl0_inst_AHBL_M00_interconnect_HRESP, ahbl0_inst_AHBL_M00_interconnect_HSELx, 
        ahbl0_inst_AHBL_M00_interconnect_HWRITE, ahbl0_inst_AHBL_M01_interconnect_HREADYOUT, 
        ahbl0_inst_AHBL_M01_interconnect_HREADY, ahbl0_inst_AHBL_M01_interconnect_HRESP, 
        ahbl0_inst_AHBL_M01_interconnect_HSELx, ahbl0_inst_AHBL_M01_interconnect_HWRITE, 
        ahbl0_inst_AHBL_M02_interconnect_HMASTLOCK, ahbl0_inst_AHBL_M02_interconnect_HREADYOUT, 
        ahbl0_inst_AHBL_M02_interconnect_HREADY, ahbl0_inst_AHBL_M02_interconnect_HRESP, 
        ahbl0_inst_AHBL_M02_interconnect_HSELx, ahbl0_inst_AHBL_M02_interconnect_HWRITE, 
        cpu0_inst_AHBL_M1_DATA_interconnect_HMASTLOCK, cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT, 
        cpu0_inst_AHBL_M1_DATA_interconnect_HRESP, cpu0_inst_AHBL_M1_DATA_interconnect_HWRITE, 
        ahbl_uart_inst_INT_interconnect_IRQ;
    wire [31:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HADDR;
    wire [2:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HBURST;
    wire [3:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HPROT;
    wire [31:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HRDATA;
    wire [2:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HSIZE;
    wire [1:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HTRANS;
    wire [31:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HWDATA;
    
    wire cpu0_inst_AHBL_M0_INSTR_interconnect_HMASTLOCK, cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT, 
        cpu0_inst_AHBL_M0_INSTR_interconnect_HRESP, cpu0_inst_AHBL_M0_INSTR_interconnect_HWRITE;
    
    
    ahbl0 ahbl0_inst (.ahbl_m00_haddr_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HADDR}), 
          .ahbl_m00_hburst_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HBURST}), 
          .ahbl_m00_hprot_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HPROT}), 
          .ahbl_m00_hrdata_mstr_i({ahbl0_inst_AHBL_M00_interconnect_HRDATA}), 
          .ahbl_m00_hsize_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HSIZE}), 
          .ahbl_m00_htrans_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HTRANS}), 
          .ahbl_m00_hwdata_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HWDATA}), 
          .ahbl_m01_haddr_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HADDR}), 
          .ahbl_m01_hburst_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HBURST}), 
          .ahbl_m01_hrdata_mstr_i({ahbl0_inst_AHBL_M01_interconnect_HRDATA}), 
          .ahbl_m01_hsize_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HSIZE}), 
          .ahbl_m01_htrans_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HTRANS}), 
          .ahbl_m01_hwdata_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HWDATA}), 
          .ahbl_m02_haddr_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HADDR}), 
          .ahbl_m02_hburst_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HBURST}), 
          .ahbl_m02_hprot_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HPROT}), 
          .ahbl_m02_hrdata_mstr_i({ahbl0_inst_AHBL_M02_interconnect_HRDATA}), 
          .ahbl_m02_hsize_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HSIZE}), 
          .ahbl_m02_htrans_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HTRANS}), 
          .ahbl_m02_hwdata_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HWDATA}), 
          .ahbl_s00_haddr_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HADDR}), 
          .ahbl_s00_hburst_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HBURST}), 
          .ahbl_s00_hprot_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HPROT}), 
          .ahbl_s00_hrdata_slv_o({cpu0_inst_AHBL_M1_DATA_interconnect_HRDATA}), 
          .ahbl_s00_hsize_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HSIZE}), 
          .ahbl_s00_htrans_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HTRANS}), 
          .ahbl_s00_hwdata_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HWDATA}), 
          .ahbl_hclk_i(clk_i), .ahbl_hresetn_i(cpu0_inst_system_resetn_o_net), 
          .ahbl_m00_hmastlock_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HMASTLOCK), 
          .ahbl_m00_hready_mstr_i(ahbl0_inst_AHBL_M00_interconnect_HREADYOUT), 
          .ahbl_m00_hready_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HREADY), 
          .ahbl_m00_hresp_mstr_i(ahbl0_inst_AHBL_M00_interconnect_HRESP), 
          .ahbl_m00_hsel_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HSELx), .ahbl_m00_hwrite_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HWRITE), 
          .ahbl_m01_hready_mstr_i(ahbl0_inst_AHBL_M01_interconnect_HREADYOUT), 
          .ahbl_m01_hready_mstr_o(ahbl0_inst_AHBL_M01_interconnect_HREADY), 
          .ahbl_m01_hresp_mstr_i(ahbl0_inst_AHBL_M01_interconnect_HRESP), 
          .ahbl_m01_hsel_mstr_o(ahbl0_inst_AHBL_M01_interconnect_HSELx), .ahbl_m01_hwrite_mstr_o(ahbl0_inst_AHBL_M01_interconnect_HWRITE), 
          .ahbl_m02_hmastlock_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HMASTLOCK), 
          .ahbl_m02_hready_mstr_i(ahbl0_inst_AHBL_M02_interconnect_HREADYOUT), 
          .ahbl_m02_hready_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HREADY), 
          .ahbl_m02_hresp_mstr_i(ahbl0_inst_AHBL_M02_interconnect_HRESP), 
          .ahbl_m02_hsel_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HSELx), .ahbl_m02_hwrite_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HWRITE), 
          .ahbl_s00_hmastlock_slv_i(cpu0_inst_AHBL_M1_DATA_interconnect_HMASTLOCK), 
          .ahbl_s00_hready_slv_i(cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT), 
          .ahbl_s00_hreadyout_slv_o(cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT), 
          .ahbl_s00_hresp_slv_o(cpu0_inst_AHBL_M1_DATA_interconnect_HRESP), 
          .ahbl_s00_hsel_slv_i(1'b1), .ahbl_s00_hwrite_slv_i(cpu0_inst_AHBL_M1_DATA_interconnect_HWRITE));
    defparam ahbl0_inst.FULL_DECODE_EN = 1;
    defparam ahbl0_inst.S0_ADDR_RANGE = 32'h00001000;
    defparam ahbl0_inst.S0_BASE_ADDR = 32'h00002000;
    defparam ahbl0_inst.S1_ADDR_RANGE = 32'h00000400;
    defparam ahbl0_inst.S1_BASE_ADDR = 32'h00003000;
    defparam ahbl0_inst.S2_ADDR_RANGE = 32'h00000400;
    defparam ahbl0_inst.S2_BASE_ADDR = 32'h00005000;
    ahbl_uart ahbl_uart_inst (.ahbl_haddr_i({ahbl0_inst_AHBL_M02_interconnect_HADDR}), 
            .ahbl_hburst_i({ahbl0_inst_AHBL_M02_interconnect_HBURST}), .ahbl_hprot_i({ahbl0_inst_AHBL_M02_interconnect_HPROT}), 
            .ahbl_hrdata_o({ahbl0_inst_AHBL_M02_interconnect_HRDATA}), .ahbl_hsize_i({ahbl0_inst_AHBL_M02_interconnect_HSIZE}), 
            .ahbl_htrans_i({ahbl0_inst_AHBL_M02_interconnect_HTRANS}), .ahbl_hwdata_i({ahbl0_inst_AHBL_M02_interconnect_HWDATA}), 
            .ahbl_hmastlock_i(ahbl0_inst_AHBL_M02_interconnect_HMASTLOCK), 
            .ahbl_hready_i(ahbl0_inst_AHBL_M02_interconnect_HREADY), .ahbl_hreadyout_o(ahbl0_inst_AHBL_M02_interconnect_HREADYOUT), 
            .ahbl_hresp_o(ahbl0_inst_AHBL_M02_interconnect_HRESP), .ahbl_hsel_i(ahbl0_inst_AHBL_M02_interconnect_HSELx), 
            .ahbl_hwrite_i(ahbl0_inst_AHBL_M02_interconnect_HWRITE), .clk(clk_i), 
            .i_rxd(uart_rxd_00_i), .int_o(ahbl_uart_inst_INT_interconnect_IRQ), 
            .o_txd(uart_txd_00_o), .resetn(cpu0_inst_system_resetn_o_net));
    cpu0 cpu0_inst (.ahbl_m_data_haddr_o({cpu0_inst_AHBL_M1_DATA_interconnect_HADDR}), 
         .ahbl_m_data_hburst_o({cpu0_inst_AHBL_M1_DATA_interconnect_HBURST}), 
         .ahbl_m_data_hprot_o({cpu0_inst_AHBL_M1_DATA_interconnect_HPROT}), 
         .ahbl_m_data_hrdata_i({cpu0_inst_AHBL_M1_DATA_interconnect_HRDATA}), 
         .ahbl_m_data_hsize_o({cpu0_inst_AHBL_M1_DATA_interconnect_HSIZE}), 
         .ahbl_m_data_htrans_o({cpu0_inst_AHBL_M1_DATA_interconnect_HTRANS}), 
         .ahbl_m_data_hwdata_o({cpu0_inst_AHBL_M1_DATA_interconnect_HWDATA}), 
         .ahbl_m_instr_haddr_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HADDR}), 
         .ahbl_m_instr_hburst_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HBURST}), 
         .ahbl_m_instr_hprot_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HPROT}), 
         .ahbl_m_instr_hrdata_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HRDATA}), 
         .ahbl_m_instr_hsize_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HSIZE}), 
         .ahbl_m_instr_htrans_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HTRANS}), 
         .ahbl_m_instr_hwdata_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HWDATA}), 
         .ahbl_m_data_hmastlock_o(cpu0_inst_AHBL_M1_DATA_interconnect_HMASTLOCK), 
         .ahbl_m_data_hready_i(cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT), 
         .ahbl_m_data_hresp_i(cpu0_inst_AHBL_M1_DATA_interconnect_HRESP), 
         .ahbl_m_data_hwrite_o(cpu0_inst_AHBL_M1_DATA_interconnect_HWRITE), 
         .ahbl_m_instr_hmastlock_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HMASTLOCK), 
         .ahbl_m_instr_hready_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT), 
         .ahbl_m_instr_hresp_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HRESP), 
         .ahbl_m_instr_hwrite_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HWRITE), 
         .clk_i(clk_i), .irq1_i(ahbl_uart_inst_INT_interconnect_IRQ), .rst_n_i(rstn_i), 
         .system_resetn_o(cpu0_inst_system_resetn_o_net));
    gpio0 gpio0_inst (.ahbl_haddr_i({ahbl0_inst_AHBL_M01_interconnect_HADDR}), 
          .ahbl_hburst_i({ahbl0_inst_AHBL_M01_interconnect_HBURST}), .ahbl_hrdata_o({ahbl0_inst_AHBL_M01_interconnect_HRDATA}), 
          .ahbl_hsize_i({ahbl0_inst_AHBL_M01_interconnect_HSIZE}), .ahbl_htrans_i({ahbl0_inst_AHBL_M01_interconnect_HTRANS}), 
          .ahbl_hwdata_i({ahbl0_inst_AHBL_M01_interconnect_HWDATA}), .gpio_io({gpio0_io}), 
          .ahbl_hclk_i(clk_i), .ahbl_hready_i(ahbl0_inst_AHBL_M01_interconnect_HREADY), 
          .ahbl_hreadyout_o(ahbl0_inst_AHBL_M01_interconnect_HREADYOUT), .ahbl_hresetn_i(cpu0_inst_system_resetn_o_net), 
          .ahbl_hresp_o(ahbl0_inst_AHBL_M01_interconnect_HRESP), .ahbl_hsel_i(ahbl0_inst_AHBL_M01_interconnect_HSELx), 
          .ahbl_hwrite_i(ahbl0_inst_AHBL_M01_interconnect_HWRITE));
    system0 system0_inst (.ahbl_s0_haddr_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HADDR}), 
            .ahbl_s0_hburst_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HBURST}), 
            .ahbl_s0_hprot_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HPROT}), 
            .ahbl_s0_hrdata_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HRDATA}), 
            .ahbl_s0_hsize_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HSIZE}), 
            .ahbl_s0_htrans_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HTRANS}), 
            .ahbl_s0_hwdata_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HWDATA}), 
            .ahbl_hclk_i(clk_i), .ahbl_hresetn_i(cpu0_inst_system_resetn_o_net), 
            .ahbl_s0_hmastlock_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HMASTLOCK), 
            .ahbl_s0_hready_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT), 
            .ahbl_s0_hreadyout_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT), 
            .ahbl_s0_hresp_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HRESP), 
            .ahbl_s0_hsel_i(1'b1), .ahbl_s0_hwrite_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HWRITE));
    defparam system0_inst.MEM_ID = "system0";
    system1 system1_inst (.ahbl_s0_haddr_i({ahbl0_inst_AHBL_M00_interconnect_HADDR}), 
            .ahbl_s0_hburst_i({ahbl0_inst_AHBL_M00_interconnect_HBURST}), 
            .ahbl_s0_hprot_i({ahbl0_inst_AHBL_M00_interconnect_HPROT}), .ahbl_s0_hrdata_o({ahbl0_inst_AHBL_M00_interconnect_HRDATA}), 
            .ahbl_s0_hsize_i({ahbl0_inst_AHBL_M00_interconnect_HSIZE}), .ahbl_s0_htrans_i({ahbl0_inst_AHBL_M00_interconnect_HTRANS}), 
            .ahbl_s0_hwdata_i({ahbl0_inst_AHBL_M00_interconnect_HWDATA}), 
            .ahbl_hclk_i(clk_i), .ahbl_hresetn_i(cpu0_inst_system_resetn_o_net), 
            .ahbl_s0_hmastlock_i(ahbl0_inst_AHBL_M00_interconnect_HMASTLOCK), 
            .ahbl_s0_hready_i(ahbl0_inst_AHBL_M00_interconnect_HREADY), .ahbl_s0_hreadyout_o(ahbl0_inst_AHBL_M00_interconnect_HREADYOUT), 
            .ahbl_s0_hresp_o(ahbl0_inst_AHBL_M00_interconnect_HRESP), .ahbl_s0_hsel_i(ahbl0_inst_AHBL_M00_interconnect_HSELx), 
            .ahbl_s0_hwrite_i(ahbl0_inst_AHBL_M00_interconnect_HWRITE));
    defparam system1_inst.MEM_ID = "system1";
    
endmodule

