// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR 
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE. 
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

/* synthesis translate_off*/
`define SBP_SIMULATION
/* synthesis translate_on*/
`ifndef SBP_SIMULATION
`define SBP_SYNTHESIS
`endif



//
// Verific Verilog Description of module ice40_nano
//
module ice40_nano (gpio0_io, ice40_ip_addr, ice40_ip_int, ice40_ip_rdata, 
            ice40_ip_wdata, sram_addr, sram_din, sram_dout, sram_maskwe, 
            clk_i, ice40_ip_ack, ice40_ip_stb, ice40_ip_we, rstn_i, 
            sram_re, sram_read_valid, sram_we, sram_write_done, uart_rxd_00_i, 
            uart_txd_00_o);
    inout [7:0]gpio0_io;
    output [7:0]ice40_ip_addr;
    input [1:0]ice40_ip_int;
    input [7:0]ice40_ip_rdata;
    output [7:0]ice40_ip_wdata;
    output [31:0]sram_addr;
    output [31:0]sram_din;
    input [31:0]sram_dout;
    output [3:0]sram_maskwe;
    input clk_i;
    input ice40_ip_ack;
    output ice40_ip_stb;
    output ice40_ip_we;
    input rstn_i;
    output sram_re;
    input sram_read_valid;
    output sram_we;
    input sram_write_done;
    input uart_rxd_00_i;
    output uart_txd_00_o;
    
    wire [31:0]ahbl0_inst_AHBL_M00_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M00_interconnect_HBURST;
    wire [31:0]ahbl0_inst_AHBL_M00_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M00_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M00_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M00_interconnect_HWDATA;
    
    wire ahbl0_inst_AHBL_M00_interconnect_HREADY, ahbl0_inst_AHBL_M00_interconnect_HREADYOUT, 
        cpu0_inst_system_resetn_o_net, ahbl0_inst_AHBL_M00_interconnect_HRESP, 
        ahbl0_inst_AHBL_M00_interconnect_HSELx, ahbl0_inst_AHBL_M00_interconnect_HWRITE;
    wire [31:0]ahbl0_inst_AHBL_M01_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M01_interconnect_HBURST;
    wire [31:0]ahbl0_inst_AHBL_M01_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M01_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M01_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M01_interconnect_HWDATA;
    wire [31:0]ahbl0_inst_AHBL_M02_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M02_interconnect_HBURST;
    wire [31:0]ahbl0_inst_AHBL_M02_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M02_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M02_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M02_interconnect_HWDATA;
    wire [31:0]ahbl0_inst_AHBL_M03_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M03_interconnect_HBURST;
    wire [31:0]ahbl0_inst_AHBL_M03_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M03_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M03_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M03_interconnect_HWDATA;
    wire [31:0]ahbl0_inst_AHBL_M04_interconnect_HADDR;
    wire [2:0]ahbl0_inst_AHBL_M04_interconnect_HBURST;
    wire [31:0]ahbl0_inst_AHBL_M04_interconnect_HRDATA;
    wire [2:0]ahbl0_inst_AHBL_M04_interconnect_HSIZE;
    wire [1:0]ahbl0_inst_AHBL_M04_interconnect_HTRANS;
    wire [31:0]ahbl0_inst_AHBL_M04_interconnect_HWDATA;
    wire [31:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HADDR;
    wire [2:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HBURST;
    wire [3:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HPROT;
    wire [31:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HRDATA;
    wire [2:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HSIZE;
    wire [1:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HTRANS;
    wire [31:0]cpu0_inst_AHBL_M0_INSTR_interconnect_HWDATA;
    wire [31:0]cpu0_inst_AHBL_M1_DATA_interconnect_HADDR;
    wire [2:0]cpu0_inst_AHBL_M1_DATA_interconnect_HBURST;
    wire [3:0]cpu0_inst_AHBL_M1_DATA_interconnect_HPROT;
    wire [31:0]cpu0_inst_AHBL_M1_DATA_interconnect_HRDATA;
    wire [2:0]cpu0_inst_AHBL_M1_DATA_interconnect_HSIZE;
    wire [1:0]cpu0_inst_AHBL_M1_DATA_interconnect_HTRANS;
    wire [31:0]cpu0_inst_AHBL_M1_DATA_interconnect_HWDATA;
    
    wire ahbl0_inst_AHBL_M01_interconnect_HREADYOUT, ahbl0_inst_AHBL_M01_interconnect_HREADY, 
        ahbl0_inst_AHBL_M01_interconnect_HRESP, ahbl0_inst_AHBL_M01_interconnect_HSELx, 
        ahbl0_inst_AHBL_M01_interconnect_HWRITE, ahbl0_inst_AHBL_M02_interconnect_HREADYOUT, 
        ahbl0_inst_AHBL_M02_interconnect_HREADY, ahbl0_inst_AHBL_M02_interconnect_HRESP, 
        ahbl0_inst_AHBL_M02_interconnect_HSELx, ahbl0_inst_AHBL_M02_interconnect_HWRITE, 
        ahbl0_inst_AHBL_M03_interconnect_HREADYOUT, ahbl0_inst_AHBL_M03_interconnect_HREADY, 
        ahbl0_inst_AHBL_M03_interconnect_HRESP, ahbl0_inst_AHBL_M03_interconnect_HSELx, 
        ahbl0_inst_AHBL_M03_interconnect_HWRITE, ahbl0_inst_AHBL_M04_interconnect_HREADYOUT, 
        ahbl0_inst_AHBL_M04_interconnect_HREADY, ahbl0_inst_AHBL_M04_interconnect_HRESP, 
        ahbl0_inst_AHBL_M04_interconnect_HSELx, ahbl0_inst_AHBL_M04_interconnect_HWRITE, 
        cpu0_inst_AHBL_M0_INSTR_interconnect_HMASTLOCK, cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT, 
        cpu0_inst_AHBL_M0_INSTR_interconnect_HRESP, cpu0_inst_AHBL_M0_INSTR_interconnect_HWRITE, 
        cpu0_inst_AHBL_M1_DATA_interconnect_HMASTLOCK, cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT, 
        cpu0_inst_AHBL_M1_DATA_interconnect_HRESP, cpu0_inst_AHBL_M1_DATA_interconnect_HWRITE;
    wire [31:0]timer_inst_systime_o_netbus;
    
    wire ahbl_uart_inst_INT_interconnect_IRQ, timer_inst_IRQ_interconnect_IRQ;
    
    
    ahb_spsram ahb_spsram_inst (.HADDR({ahbl0_inst_AHBL_M00_interconnect_HADDR}), 
            .HBURST({ahbl0_inst_AHBL_M00_interconnect_HBURST}), .HRDATA({ahbl0_inst_AHBL_M00_interconnect_HRDATA}), 
            .HSIZE({ahbl0_inst_AHBL_M00_interconnect_HSIZE}), .HTRANS({ahbl0_inst_AHBL_M00_interconnect_HTRANS}), 
            .HWDATA({ahbl0_inst_AHBL_M00_interconnect_HWDATA}), .sram_addr({sram_addr}), 
            .sram_din({sram_din}), .sram_dout({sram_dout}), .sram_maskwe({sram_maskwe}), 
            .HCLK(clk_i), .HREADY(ahbl0_inst_AHBL_M00_interconnect_HREADY), 
            .HREADYOUT(ahbl0_inst_AHBL_M00_interconnect_HREADYOUT), .HRESETn(cpu0_inst_system_resetn_o_net), 
            .HRESP(ahbl0_inst_AHBL_M00_interconnect_HRESP), .HSEL(ahbl0_inst_AHBL_M00_interconnect_HSELx), 
            .HWRITE(ahbl0_inst_AHBL_M00_interconnect_HWRITE), .sram_re(sram_re), 
            .sram_read_valid(sram_read_valid), .sram_we(sram_we), .sram_write_done(sram_write_done));
    ahbl0 ahbl0_inst (.ahbl_m00_haddr_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HADDR}), 
          .ahbl_m00_hburst_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HBURST}), 
          .ahbl_m00_hrdata_mstr_i({ahbl0_inst_AHBL_M00_interconnect_HRDATA}), 
          .ahbl_m00_hsize_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HSIZE}), 
          .ahbl_m00_htrans_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HTRANS}), 
          .ahbl_m00_hwdata_mstr_o({ahbl0_inst_AHBL_M00_interconnect_HWDATA}), 
          .ahbl_m01_haddr_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HADDR}), 
          .ahbl_m01_hburst_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HBURST}), 
          .ahbl_m01_hrdata_mstr_i({ahbl0_inst_AHBL_M01_interconnect_HRDATA}), 
          .ahbl_m01_hsize_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HSIZE}), 
          .ahbl_m01_htrans_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HTRANS}), 
          .ahbl_m01_hwdata_mstr_o({ahbl0_inst_AHBL_M01_interconnect_HWDATA}), 
          .ahbl_m02_haddr_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HADDR}), 
          .ahbl_m02_hburst_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HBURST}), 
          .ahbl_m02_hrdata_mstr_i({ahbl0_inst_AHBL_M02_interconnect_HRDATA}), 
          .ahbl_m02_hsize_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HSIZE}), 
          .ahbl_m02_htrans_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HTRANS}), 
          .ahbl_m02_hwdata_mstr_o({ahbl0_inst_AHBL_M02_interconnect_HWDATA}), 
          .ahbl_m03_haddr_mstr_o({ahbl0_inst_AHBL_M03_interconnect_HADDR}), 
          .ahbl_m03_hburst_mstr_o({ahbl0_inst_AHBL_M03_interconnect_HBURST}), 
          .ahbl_m03_hrdata_mstr_i({ahbl0_inst_AHBL_M03_interconnect_HRDATA}), 
          .ahbl_m03_hsize_mstr_o({ahbl0_inst_AHBL_M03_interconnect_HSIZE}), 
          .ahbl_m03_htrans_mstr_o({ahbl0_inst_AHBL_M03_interconnect_HTRANS}), 
          .ahbl_m03_hwdata_mstr_o({ahbl0_inst_AHBL_M03_interconnect_HWDATA}), 
          .ahbl_m04_haddr_mstr_o({ahbl0_inst_AHBL_M04_interconnect_HADDR}), 
          .ahbl_m04_hburst_mstr_o({ahbl0_inst_AHBL_M04_interconnect_HBURST}), 
          .ahbl_m04_hrdata_mstr_i({ahbl0_inst_AHBL_M04_interconnect_HRDATA}), 
          .ahbl_m04_hsize_mstr_o({ahbl0_inst_AHBL_M04_interconnect_HSIZE}), 
          .ahbl_m04_htrans_mstr_o({ahbl0_inst_AHBL_M04_interconnect_HTRANS}), 
          .ahbl_m04_hwdata_mstr_o({ahbl0_inst_AHBL_M04_interconnect_HWDATA}), 
          .ahbl_s00_haddr_slv_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HADDR}), 
          .ahbl_s00_hburst_slv_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HBURST}), 
          .ahbl_s00_hprot_slv_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HPROT}), 
          .ahbl_s00_hrdata_slv_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HRDATA}), 
          .ahbl_s00_hsize_slv_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HSIZE}), 
          .ahbl_s00_htrans_slv_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HTRANS}), 
          .ahbl_s00_hwdata_slv_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HWDATA}), 
          .ahbl_s01_haddr_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HADDR}), 
          .ahbl_s01_hburst_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HBURST}), 
          .ahbl_s01_hprot_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HPROT}), 
          .ahbl_s01_hrdata_slv_o({cpu0_inst_AHBL_M1_DATA_interconnect_HRDATA}), 
          .ahbl_s01_hsize_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HSIZE}), 
          .ahbl_s01_htrans_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HTRANS}), 
          .ahbl_s01_hwdata_slv_i({cpu0_inst_AHBL_M1_DATA_interconnect_HWDATA}), 
          .ahbl_hclk_i(clk_i), .ahbl_hresetn_i(cpu0_inst_system_resetn_o_net), 
          .ahbl_m00_hready_mstr_i(ahbl0_inst_AHBL_M00_interconnect_HREADYOUT), 
          .ahbl_m00_hready_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HREADY), 
          .ahbl_m00_hresp_mstr_i(ahbl0_inst_AHBL_M00_interconnect_HRESP), 
          .ahbl_m00_hsel_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HSELx), .ahbl_m00_hwrite_mstr_o(ahbl0_inst_AHBL_M00_interconnect_HWRITE), 
          .ahbl_m01_hready_mstr_i(ahbl0_inst_AHBL_M01_interconnect_HREADYOUT), 
          .ahbl_m01_hready_mstr_o(ahbl0_inst_AHBL_M01_interconnect_HREADY), 
          .ahbl_m01_hresp_mstr_i(ahbl0_inst_AHBL_M01_interconnect_HRESP), 
          .ahbl_m01_hsel_mstr_o(ahbl0_inst_AHBL_M01_interconnect_HSELx), .ahbl_m01_hwrite_mstr_o(ahbl0_inst_AHBL_M01_interconnect_HWRITE), 
          .ahbl_m02_hready_mstr_i(ahbl0_inst_AHBL_M02_interconnect_HREADYOUT), 
          .ahbl_m02_hready_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HREADY), 
          .ahbl_m02_hresp_mstr_i(ahbl0_inst_AHBL_M02_interconnect_HRESP), 
          .ahbl_m02_hsel_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HSELx), .ahbl_m02_hwrite_mstr_o(ahbl0_inst_AHBL_M02_interconnect_HWRITE), 
          .ahbl_m03_hready_mstr_i(ahbl0_inst_AHBL_M03_interconnect_HREADYOUT), 
          .ahbl_m03_hready_mstr_o(ahbl0_inst_AHBL_M03_interconnect_HREADY), 
          .ahbl_m03_hresp_mstr_i(ahbl0_inst_AHBL_M03_interconnect_HRESP), 
          .ahbl_m03_hsel_mstr_o(ahbl0_inst_AHBL_M03_interconnect_HSELx), .ahbl_m03_hwrite_mstr_o(ahbl0_inst_AHBL_M03_interconnect_HWRITE), 
          .ahbl_m04_hready_mstr_i(ahbl0_inst_AHBL_M04_interconnect_HREADYOUT), 
          .ahbl_m04_hready_mstr_o(ahbl0_inst_AHBL_M04_interconnect_HREADY), 
          .ahbl_m04_hresp_mstr_i(ahbl0_inst_AHBL_M04_interconnect_HRESP), 
          .ahbl_m04_hsel_mstr_o(ahbl0_inst_AHBL_M04_interconnect_HSELx), .ahbl_m04_hwrite_mstr_o(ahbl0_inst_AHBL_M04_interconnect_HWRITE), 
          .ahbl_s00_hmastlock_slv_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HMASTLOCK), 
          .ahbl_s00_hready_slv_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT), 
          .ahbl_s00_hreadyout_slv_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT), 
          .ahbl_s00_hresp_slv_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HRESP), 
          .ahbl_s00_hsel_slv_i(1'b1), .ahbl_s00_hwrite_slv_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HWRITE), 
          .ahbl_s01_hmastlock_slv_i(cpu0_inst_AHBL_M1_DATA_interconnect_HMASTLOCK), 
          .ahbl_s01_hready_slv_i(cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT), 
          .ahbl_s01_hreadyout_slv_o(cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT), 
          .ahbl_s01_hresp_slv_o(cpu0_inst_AHBL_M1_DATA_interconnect_HRESP), 
          .ahbl_s01_hsel_slv_i(1'b1), .ahbl_s01_hwrite_slv_i(cpu0_inst_AHBL_M1_DATA_interconnect_HWRITE));
    defparam ahbl0_inst.FULL_DECODE_EN = 1;
    defparam ahbl0_inst.S0_ADDR_RANGE = 32'h00020000;
    defparam ahbl0_inst.S0_BASE_ADDR = 32'h00000000;
    defparam ahbl0_inst.S1_ADDR_RANGE = 32'h00000400;
    defparam ahbl0_inst.S1_BASE_ADDR = 32'h00020000;
    defparam ahbl0_inst.S2_ADDR_RANGE = 32'h00000400;
    defparam ahbl0_inst.S2_BASE_ADDR = 32'h00025000;
    defparam ahbl0_inst.S3_ADDR_RANGE = 32'h00000400;
    defparam ahbl0_inst.S3_BASE_ADDR = 32'h00030000;
    defparam ahbl0_inst.S4_ADDR_RANGE = 32'h00000400;
    defparam ahbl0_inst.S4_BASE_ADDR = 32'h00023000;
    ahbl_uart ahbl_uart_inst (.ahbl_haddr_i({ahbl0_inst_AHBL_M02_interconnect_HADDR}), 
            .ahbl_hburst_i({ahbl0_inst_AHBL_M02_interconnect_HBURST}), .ahbl_hrdata_o({ahbl0_inst_AHBL_M02_interconnect_HRDATA}), 
            .ahbl_hsize_i({ahbl0_inst_AHBL_M02_interconnect_HSIZE}), .ahbl_htrans_i({ahbl0_inst_AHBL_M02_interconnect_HTRANS}), 
            .ahbl_hwdata_i({ahbl0_inst_AHBL_M02_interconnect_HWDATA}), .systime_i({timer_inst_systime_o_netbus}), 
            .ahbl_hready_i(ahbl0_inst_AHBL_M02_interconnect_HREADY), .ahbl_hreadyout_o(ahbl0_inst_AHBL_M02_interconnect_HREADYOUT), 
            .ahbl_hresp_o(ahbl0_inst_AHBL_M02_interconnect_HRESP), .ahbl_hsel_i(ahbl0_inst_AHBL_M02_interconnect_HSELx), 
            .ahbl_hwrite_i(ahbl0_inst_AHBL_M02_interconnect_HWRITE), .clk(clk_i), 
            .i_rxd(uart_rxd_00_i), .int_o(ahbl_uart_inst_INT_interconnect_IRQ), 
            .o_txd(uart_txd_00_o), .resetn(cpu0_inst_system_resetn_o_net));
    cpu0 cpu0_inst (.ahbl_m_data_haddr_o({cpu0_inst_AHBL_M1_DATA_interconnect_HADDR}), 
         .ahbl_m_data_hburst_o({cpu0_inst_AHBL_M1_DATA_interconnect_HBURST}), 
         .ahbl_m_data_hprot_o({cpu0_inst_AHBL_M1_DATA_interconnect_HPROT}), 
         .ahbl_m_data_hrdata_i({cpu0_inst_AHBL_M1_DATA_interconnect_HRDATA}), 
         .ahbl_m_data_hsize_o({cpu0_inst_AHBL_M1_DATA_interconnect_HSIZE}), 
         .ahbl_m_data_htrans_o({cpu0_inst_AHBL_M1_DATA_interconnect_HTRANS}), 
         .ahbl_m_data_hwdata_o({cpu0_inst_AHBL_M1_DATA_interconnect_HWDATA}), 
         .ahbl_m_instr_haddr_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HADDR}), 
         .ahbl_m_instr_hburst_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HBURST}), 
         .ahbl_m_instr_hprot_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HPROT}), 
         .ahbl_m_instr_hrdata_i({cpu0_inst_AHBL_M0_INSTR_interconnect_HRDATA}), 
         .ahbl_m_instr_hsize_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HSIZE}), 
         .ahbl_m_instr_htrans_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HTRANS}), 
         .ahbl_m_instr_hwdata_o({cpu0_inst_AHBL_M0_INSTR_interconnect_HWDATA}), 
         .ahbl_m_data_hmastlock_o(cpu0_inst_AHBL_M1_DATA_interconnect_HMASTLOCK), 
         .ahbl_m_data_hready_i(cpu0_inst_AHBL_M1_DATA_interconnect_HREADYOUT), 
         .ahbl_m_data_hresp_i(cpu0_inst_AHBL_M1_DATA_interconnect_HRESP), 
         .ahbl_m_data_hwrite_o(cpu0_inst_AHBL_M1_DATA_interconnect_HWRITE), 
         .ahbl_m_instr_hmastlock_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HMASTLOCK), 
         .ahbl_m_instr_hready_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HREADYOUT), 
         .ahbl_m_instr_hresp_i(cpu0_inst_AHBL_M0_INSTR_interconnect_HRESP), 
         .ahbl_m_instr_hwrite_o(cpu0_inst_AHBL_M0_INSTR_interconnect_HWRITE), 
         .clk_i(clk_i), .irq0_i(timer_inst_IRQ_interconnect_IRQ), .irq1_i(ahbl_uart_inst_INT_interconnect_IRQ), 
         .rst_n_i(rstn_i), .system_resetn_o(cpu0_inst_system_resetn_o_net));
    gpio0 gpio0_inst (.ahbl_haddr_i({ahbl0_inst_AHBL_M04_interconnect_HADDR}), 
          .ahbl_hburst_i({ahbl0_inst_AHBL_M04_interconnect_HBURST}), .ahbl_hrdata_o({ahbl0_inst_AHBL_M04_interconnect_HRDATA}), 
          .ahbl_hsize_i({ahbl0_inst_AHBL_M04_interconnect_HSIZE}), .ahbl_htrans_i({ahbl0_inst_AHBL_M04_interconnect_HTRANS}), 
          .ahbl_hwdata_i({ahbl0_inst_AHBL_M04_interconnect_HWDATA}), .gpio_io({gpio0_io}), 
          .ahbl_hready_i(ahbl0_inst_AHBL_M04_interconnect_HREADY), .ahbl_hreadyout_o(ahbl0_inst_AHBL_M04_interconnect_HREADYOUT), 
          .ahbl_hresp_o(ahbl0_inst_AHBL_M04_interconnect_HRESP), .ahbl_hsel_i(ahbl0_inst_AHBL_M04_interconnect_HSELx), 
          .ahbl_hwrite_i(ahbl0_inst_AHBL_M04_interconnect_HWRITE), .clk_i(clk_i), 
          .resetn_i(cpu0_inst_system_resetn_o_net));
    ice40_ip_interface ice40_ip_interface_inst (.HADDR({ahbl0_inst_AHBL_M01_interconnect_HADDR}), 
            .HBURST({ahbl0_inst_AHBL_M01_interconnect_HBURST}), .HRDATA({ahbl0_inst_AHBL_M01_interconnect_HRDATA}), 
            .HSIZE({ahbl0_inst_AHBL_M01_interconnect_HSIZE}), .HTRANS({ahbl0_inst_AHBL_M01_interconnect_HTRANS}), 
            .HWDATA({ahbl0_inst_AHBL_M01_interconnect_HWDATA}), .ip_addr_o({ice40_ip_addr}), 
            .ip_int_i({ice40_ip_int}), .ip_rdata_i({ice40_ip_rdata}), .ip_wdata_o({ice40_ip_wdata}), 
            .HREADY(ahbl0_inst_AHBL_M01_interconnect_HREADY), .HREADYOUT(ahbl0_inst_AHBL_M01_interconnect_HREADYOUT), 
            .HRESP(ahbl0_inst_AHBL_M01_interconnect_HRESP), .HSEL(ahbl0_inst_AHBL_M01_interconnect_HSELx), 
            .HWRITE(ahbl0_inst_AHBL_M01_interconnect_HWRITE), .clk(clk_i), 
            .ip_ack_i(ice40_ip_ack), .ip_stb_o(ice40_ip_stb), .ip_we_o(ice40_ip_we), 
            .resetn(cpu0_inst_system_resetn_o_net));
    timer timer_inst (.ahbl_haddr_i({ahbl0_inst_AHBL_M03_interconnect_HADDR}), 
          .ahbl_hburst_i({ahbl0_inst_AHBL_M03_interconnect_HBURST}), .ahbl_hrdata_o({ahbl0_inst_AHBL_M03_interconnect_HRDATA}), 
          .ahbl_hsize_i({ahbl0_inst_AHBL_M03_interconnect_HSIZE}), .ahbl_htrans_i({ahbl0_inst_AHBL_M03_interconnect_HTRANS}), 
          .ahbl_hwdata_i({ahbl0_inst_AHBL_M03_interconnect_HWDATA}), .systime_o({timer_inst_systime_o_netbus}), 
          .int_o(timer_inst_IRQ_interconnect_IRQ), .ahbl_hready_i(ahbl0_inst_AHBL_M03_interconnect_HREADY), 
          .ahbl_hreadyout_o(ahbl0_inst_AHBL_M03_interconnect_HREADYOUT), .ahbl_hresp_o(ahbl0_inst_AHBL_M03_interconnect_HRESP), 
          .ahbl_hsel_i(ahbl0_inst_AHBL_M03_interconnect_HSELx), .ahbl_hwrite_i(ahbl0_inst_AHBL_M03_interconnect_HWRITE), 
          .clk_i(clk_i), .resetn_i(cpu0_inst_system_resetn_o_net));
    
endmodule

