    ahbl_uart __(.clk( ),
        .i_rxd( ),
        .o_txd( ),
        .int_o( ),
        .ahbl_haddr_i( ),
        .ahbl_hburst_i( ),
        .ahbl_hprot_i( ),
        .ahbl_hrdata_o( ),
        .ahbl_hsize_i( ),
        .ahbl_htrans_i( ),
        .ahbl_hwdata_i( ),
        .ahbl_hmastlock_i( ),
        .ahbl_hready_i( ),
        .ahbl_hreadyout_o( ),
        .ahbl_hsel_i( ),
        .ahbl_hwrite_i( ),
        .resetn( ),
        .ahbl_hresp_o( ));
