
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.5
    2025 08 06 07:36:59
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="ahbl_uart", LATTICE_IP_GENERATED="1" *) module ahbl_uart (clk, 
        i_rxd, 
        o_txd, 
        int_o, 
        ahbl_haddr_i, 
        ahbl_hburst_i, 
        ahbl_hprot_i, 
        ahbl_hrdata_o, 
        ahbl_hsize_i, 
        ahbl_htrans_i, 
        ahbl_hwdata_i, 
        ahbl_hmastlock_i, 
        ahbl_hready_i, 
        ahbl_hreadyout_o, 
        ahbl_hsel_i, 
        ahbl_hwrite_i, 
        resetn, 
        ahbl_hresp_o) ;
    input clk ; 
    input i_rxd ; 
    output o_txd ; 
    output int_o ; 
    input [31:0] ahbl_haddr_i ; 
    input [2:0] ahbl_hburst_i ; 
    input [3:0] ahbl_hprot_i ; 
    output [31:0] ahbl_hrdata_o ; 
    input [2:0] ahbl_hsize_i ; 
    input [1:0] ahbl_htrans_i ; 
    input [31:0] ahbl_hwdata_i ; 
    input ahbl_hmastlock_i ; 
    input ahbl_hready_i ; 
    output ahbl_hreadyout_o ; 
    input ahbl_hsel_i ; 
    input ahbl_hwrite_i ; 
    input resetn ; 
    output ahbl_hresp_o ; 
    ahbl_uart_ipgen_lsc_uart #(.CLOCK_FREQ(24000000),
            .UART_BAUDRATE(115200),
            .BUFFER_SIZE("512")) lsc_uart_inst (.clk(clk), 
                .i_rxd(i_rxd), 
                .o_txd(o_txd), 
                .int_o(int_o), 
                .ahbl_haddr_i(ahbl_haddr_i[31:0]), 
                .ahbl_hburst_i(ahbl_hburst_i[2:0]), 
                .ahbl_hprot_i(ahbl_hprot_i[3:0]), 
                .ahbl_hrdata_o(ahbl_hrdata_o[31:0]), 
                .ahbl_hsize_i(ahbl_hsize_i[2:0]), 
                .ahbl_htrans_i(ahbl_htrans_i[1:0]), 
                .ahbl_hwdata_i(ahbl_hwdata_i[31:0]), 
                .ahbl_hmastlock_i(ahbl_hmastlock_i), 
                .ahbl_hready_i(ahbl_hready_i), 
                .ahbl_hreadyout_o(ahbl_hreadyout_o), 
                .ahbl_hsel_i(ahbl_hsel_i), 
                .ahbl_hwrite_i(ahbl_hwrite_i), 
                .resetn(resetn), 
                .ahbl_hresp_o(ahbl_hresp_o)) ; 
endmodule



// UART
// 0x00: RO : RBR : Receiver Buffer Register
// 0x00: WO : THR : Transmitter Holding Register
// 0x04: RW : IER : Interrupt Enable Register
// 0x08: RO : IIR : Interrupt Identification register
// 0x0C:      LCR : not supported
// 0x10:      reserved
// 0x14: RO : LSR : Line status register
// 0x18: RO : TXB : Tx fifo available bytes (16bits)
// 0x1C:      reserved
// 0x20: RW : DLR : Divisor LSB (8bits)
// 0x24: RW : DLR : Divisor MSB (8bits)
// 0x28: RW : DLR : Divisor (16bits)
module ahbl_uart_ipgen_lsc_uart #(parameter CLOCK_FREQ = 48000000, 
        parameter UART_BAUDRATE = 115200, 
        parameter BUFFER_SIZE = "1K") (
    // Tx buffer
    input clk,  // data interface, AHBL clock
    input i_rxd, 
    output reg o_txd, 
    output reg int_o, 
    input [31:0] ahbl_haddr_i,  // AHB address
    input [2:0] ahbl_hburst_i,  // unused
    input [3:0] ahbl_hprot_i,  // unused
    output reg [31:0] ahbl_hrdata_o,  // AHB read data
    input [2:0] ahbl_hsize_i,  // unused
    input [1:0] ahbl_htrans_i,  // AHB transfer type
    input [31:0] ahbl_hwdata_i,  // AHB write data
    input ahbl_hmastlock_i,  // unused
    input ahbl_hready_i,  // unused
    output reg ahbl_hreadyout_o,  // AHB ready signal
    output ahbl_hresp_o,  // unused
    input ahbl_hsel_i,  // AHB select
    input ahbl_hwrite_i,  // AHB write enable
    input resetn) ;
    assign ahbl_hresp_o = 1'b0 ; 
    localparam UART_BAUD_CLK = (CLOCK_FREQ / UART_BAUDRATE) ; 
    // AHBL I/F {{{
    // uart module
    reg [7:0] i_din ; 
    reg i_valid ; 
    reg [7:0] o_dout ; 
    reg o_valid ; 
    wire o_empty ; 
    wire fifo_full ; 
    wire [15:0] fifo_available_bytes ; 
    reg [15:0] r_period ; 
    reg r_rx_int ; 
    reg r_rx_int_en ; // Rx data receive int enable
    reg r_tx_int_en ; // Tx fifo empty int enable
    // AHBL
    wire [3:0] w_addr = ahbl_haddr_i[5:2] ; // same as LMMI
    wire w_we = ((ahbl_hsel_i && ahbl_htrans_i[1]) && ahbl_hwrite_i) ; 
    wire w_re = ((ahbl_hsel_i && ahbl_htrans_i[1]) && (!ahbl_hwrite_i)) ; 
    // interrupt is only for uart data reception
    reg r_valid_d ; 
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    r_valid_d <=  0 ;
                end
            else
                begin
                    r_valid_d <=  o_valid ;
                end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    int_o <=  0 ;
                end
            else
                begin
                    int_o <=  ((r_tx_int_en & o_empty) | (r_rx_int_en & r_rx_int)) ;
                end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    r_rx_int <=  0 ;
                end
            else
                if ((!r_rx_int_en)) 
                    begin
                        r_rx_int <=  0 ;
                    end
                else
                    if (w_re) 
                        begin
                            if ((w_addr == 4'h0)) 
                                begin
                                    r_rx_int <=  0 ;
                                end
                        end
                    else
                        begin
                            r_rx_int <=  (r_rx_int | (o_valid & (~r_valid_d))) ;
                        end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    ahbl_hreadyout_o <=  1'b1 ;
                end
            else
                begin
                    ahbl_hreadyout_o <=  1'b1 ;// Always ready for simplicity
                end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    ahbl_hrdata_o <=  32'd0 ;
                end
            else
                if (w_re) 
                    begin
                        if ((w_addr == 4'h0)) 
                            begin
                                // RBR
                                ahbl_hrdata_o <=  {24'd0,
                                        o_dout} ;
                            end
                        else
                            if ((w_addr == 4'h1)) 
                                begin
                                    // IER
                                    ahbl_hrdata_o <=  {30'b0,
                                            r_tx_int_en,
                                            r_rx_int_en} ;
                                end
                            else
                                if ((w_addr == 4'h2)) 
                                    begin
                                        // IIR
                                        ahbl_hrdata_o[31:8] <=  24'b0 ;
                                        ahbl_hrdata_o[7:6] <=  2'b10 ;
                                        ahbl_hrdata_o[5:3] <=  3'b000 ;
                                        ahbl_hrdata_o[2:0] <=  (r_rx_int ? 3'b100 : {1'b0,
                                                o_empty,
                                                1'b0}) ;
                                    end
                                else
                                    if ((w_addr == 4'h5)) 
                                        begin
                                            // LSR 
                                            ahbl_hrdata_o[31:8] <=  24'b0 ;
                                            ahbl_hrdata_o[7] <=  1'b0 ;
                                            ahbl_hrdata_o[6] <=  (o_empty & (~o_valid)) ;
                                            ahbl_hrdata_o[5] <=  o_empty ;
                                            ahbl_hrdata_o[4] <=  1'b0 ;// break condition, not supported
                                            ahbl_hrdata_o[3] <=  1'b0 ;// framing error, not supported
                                            ahbl_hrdata_o[2] <=  1'b0 ;// parity error, not supported
                                            ahbl_hrdata_o[1] <=  fifo_full ;
                                            ahbl_hrdata_o[0] <=  o_valid ;
                                        end
                                    else
                                        if ((w_addr == 4'h6)) 
                                            begin
                                                // tx fifo available bytes
                                                ahbl_hrdata_o[31:16] <=  16'b0 ;
                                                ahbl_hrdata_o[15:0] <=  fifo_available_bytes ;
                                            end
                                        else
                                            if ((w_addr == 4'h8)) 
                                                begin
                                                    ahbl_hrdata_o[31:8] <=  0 ;
                                                    ahbl_hrdata_o[7:0] <=  r_period[7:0] ;
                                                end
                                            else
                                                if ((w_addr == 4'h9)) 
                                                    begin
                                                        ahbl_hrdata_o[31:8] <=  0 ;
                                                        ahbl_hrdata_o[7:0] <=  r_period[15:8] ;
                                                    end
                                                else
                                                    if ((w_addr == 4'hA)) 
                                                        begin
                                                            ahbl_hrdata_o[31:16] <=  0 ;
                                                            ahbl_hrdata_o[15:0] <=  r_period ;
                                                        end
                    end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    i_din <=  0 ;
                    i_valid <=  0 ;
                end
            else
                if ((w_we && (w_addr == 4'h0))) 
                    begin
                        i_din <=  ahbl_hwdata_i[7:0] ;
                        i_valid <=  1 ;
                    end
                else
                    begin
                        i_valid <=  0 ;
                    end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    r_period <=  UART_BAUD_CLK ;
                end
            else
                if (w_we) 
                    begin
                        if ((w_addr == 4'h8)) 
                            begin
                                r_period[7:0] <=  ahbl_hwdata_i[7:0] ;
                            end
                        else
                            if ((w_addr == 4'h9)) 
                                begin
                                    r_period[15:8] <=  ahbl_hwdata_i[7:0] ;
                                end
                            else
                                if ((w_addr == 4'hA)) 
                                    begin
                                        r_period[15:0] <=  ahbl_hwdata_i[15:0] ;
                                    end
                    end
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    r_tx_int_en <=  0 ;// Tx fifo empty int enable
                    r_rx_int_en <=  0 ;// Rx data receive int enable
                end
            else
                if (w_we) 
                    begin
                        if ((w_addr == 4'h1)) 
                            begin
                                r_tx_int_en <=  ahbl_hwdata_i[1] ;
                                r_rx_int_en <=  ahbl_hwdata_i[0] ;
                            end
                    end
        end
    // AHBL I/F }}}
    // Tx side {{{
    localparam TX_FIFO_BITS = ((BUFFER_SIZE == "4K") ? 12 : ((BUFFER_SIZE == "2K") ? 11 : 10)) ; 
    wire fifo_we ; 
    wire fifo_rd ; 
    wire [7:0] fifo_dout ; 
    reg fifo_empty ; 
    reg [(TX_FIFO_BITS - 1):0] fifo_waddr ; 
    reg [(TX_FIFO_BITS - 1):0] fifo_raddr ; 
    reg [(TX_FIFO_BITS - 1):0] fifo_raddr_clk ; 
    reg [(TX_FIFO_BITS - 1):0] fifo_raddr_lat ; 
    reg r_fifo_empty ; 
    //wire		fifo_full;
    wire [(TX_FIFO_BITS - 1):0] fifo_waddr_p1 ; 
    reg [15:0] tx_period_cnt ; 
    reg [3:0] tx_bit_cnt ; // 0: IDLE, 1: Start, 2~9: bit0~7, A:Stop
    reg tx_bit_tick ; 
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                tx_bit_cnt <=  4'b0 ;
            else
                if (((tx_bit_cnt == 4'b0) && (fifo_empty == 1'b0))) 
                    tx_bit_cnt <=  4'd1 ;
                else
                    if (((tx_bit_cnt == 4'hA) && tx_bit_tick)) 
                        tx_bit_cnt <=  4'd0 ;
                    else
                        if (((tx_bit_cnt != 4'b0) && tx_bit_tick)) 
                            tx_bit_cnt <=  (tx_bit_cnt + 4'd1) ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                tx_period_cnt <=  16'b0 ;
            else
                if ((tx_bit_cnt == 4'b0)) 
                    tx_period_cnt <=  16'b0 ;
                else
                    if ((tx_period_cnt == 16'b0)) 
                        tx_period_cnt <=  r_period ;
                    else
                        tx_period_cnt <=  (tx_period_cnt - 16'd1) ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                tx_bit_tick <=  1'b0 ;
            else
                if ((tx_period_cnt == 16'd1)) 
                    tx_bit_tick <=  1'b1 ;
                else
                    tx_bit_tick <=  1'b0 ;
        end
    //assign fifo_rd = ((tx_bit_cnt == 4'hA) && (tx_period_cnt == 16'd1));
    assign fifo_rd = ((tx_bit_cnt == 4'h9) && tx_bit_tick) ; 
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((resetn == 1'b0)) 
                fifo_raddr <=  0 ;
            else
                if (fifo_rd) 
                    fifo_raddr <=  (fifo_raddr + 1) ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                o_txd <=  1'b0 ;
            else
                case (tx_bit_cnt)
                4'd1 : 
                    // start
                    o_txd <=  1'b0 ;
                4'd2 : 
                    o_txd <=  fifo_dout[0] ;
                4'd3 : 
                    o_txd <=  fifo_dout[1] ;
                4'd4 : 
                    o_txd <=  fifo_dout[2] ;
                4'd5 : 
                    o_txd <=  fifo_dout[3] ;
                4'd6 : 
                    o_txd <=  fifo_dout[4] ;
                4'd7 : 
                    o_txd <=  fifo_dout[5] ;
                4'd8 : 
                    o_txd <=  fifo_dout[6] ;
                4'd9 : 
                    o_txd <=  fifo_dout[7] ;
                default : 
                    // stop & idle
                    o_txd <=  1'b1 ;
                endcase 
        end
    always
        @(posedge clk)
        begin
            fifo_raddr_clk <=  fifo_raddr ;
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((resetn == 1'b0)) 
                fifo_raddr_lat <=  0 ;
            else
                if ((fifo_raddr_lat != fifo_raddr_clk)) 
                    fifo_raddr_lat <=  fifo_raddr_clk ;
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((resetn == 1'b0)) 
                r_fifo_empty <=  1'b1 ;
            else
                r_fifo_empty <=  (fifo_raddr_lat == fifo_waddr) ;
        end
    assign fifo_waddr_p1 = (fifo_waddr + 1) ; 
    assign fifo_we = ((!fifo_full) && i_valid) ; 
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((resetn == 1'b0)) 
                fifo_waddr <=  0 ;
            else
                if (fifo_we) 
                    fifo_waddr <=  fifo_waddr_p1 ;
        end
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((resetn == 1'b0)) 
                fifo_empty <=  1'b1 ;
            else
                fifo_empty <=  r_fifo_empty ;
        end
    assign o_empty = r_fifo_empty ; 
    assign fifo_full = (fifo_raddr_lat == fifo_waddr_p1) ; 
    reg [15:0] r_fifo_bytes ; 
    wire [15:0] w_fifo_raddr_16b ; 
    wire [15:0] w_fifo_waddr_16b ; 
    assign w_fifo_raddr_16b[15:(TX_FIFO_BITS + 1)] = 0 ; 
    assign w_fifo_raddr_16b[TX_FIFO_BITS] = (fifo_raddr_lat < fifo_waddr_p1) ; 
    assign w_fifo_raddr_16b[(TX_FIFO_BITS - 1):0] = fifo_raddr_lat ; 
    assign w_fifo_waddr_16b[15:TX_FIFO_BITS] = 0 ; 
    assign w_fifo_waddr_16b[(TX_FIFO_BITS - 1):0] = fifo_waddr_p1 ; 
    assign fifo_available_bytes = r_fifo_bytes ; 
    always
        @(posedge clk or 
            negedge resetn)
        begin
            if ((!resetn)) 
                begin
                    r_fifo_bytes <=  0 ;
                end
            else
                begin
                    r_fifo_bytes <=  (w_fifo_raddr_16b - w_fifo_waddr_16b) ;
                end
        end
    generate
        if ((BUFFER_SIZE == "4K")) 
            begin : genblk1
                // 4K byte
                dpram4096x8 u_ram4096x8_0 (.wr_clk_i(clk), 
                            .rd_clk_i(clk), 
                            .wr_clk_en_i(1'b1), 
                            .rd_en_i(1'b1), 
                            .rd_clk_en_i(1'b1), 
                            .wr_en_i(fifo_we), 
                            .wr_data_i(i_din), 
                            .wr_addr_i(fifo_waddr), 
                            .rd_addr_i(fifo_raddr), 
                            .rd_data_o(fifo_dout)) ; 
            end
        else
            if ((BUFFER_SIZE == "2K")) 
                begin : genblk1
                    // 2K byte
                    dpram2048x8 u_ram2048x8_0 (.wr_clk_i(clk), 
                                .rd_clk_i(clk), 
                                .wr_clk_en_i(1'b1), 
                                .rd_en_i(~fifo_we), 
                                .rd_clk_en_i(1'b1), 
                                .wr_en_i(fifo_we), 
                                .wr_data_i(i_din), 
                                .wr_addr_i(fifo_waddr[10:0]), 
                                .rd_addr_i(fifo_raddr[10:0]), 
                                .rd_data_o(fifo_dout)) ; 
                end
            else
                if ((BUFFER_SIZE == "1K")) 
                    begin : genblk1
                        dpram1024x8 u_ram1024x8_0 (.wr_clk_i(clk), 
                                    .rd_clk_i(clk), 
                                    .wr_clk_en_i(1'b1), 
                                    .rd_en_i(~fifo_we), 
                                    .rd_clk_en_i(1'b1), 
                                    .wr_en_i(fifo_we), 
                                    .wr_data_i(i_din), 
                                    .wr_addr_i(fifo_waddr[9:0]), 
                                    .rd_addr_i(fifo_raddr[9:0]), 
                                    .rd_data_o(fifo_dout)) ; 
                    end
                else
                    begin : genblk1
                        // 512 byte
                        dpram512x8 u_ram512x8_0 (.wr_clk_i(clk), 
                                    .rd_clk_i(clk), 
                                    .wr_clk_en_i(1'b1), 
                                    .rd_en_i(~fifo_we), 
                                    .rd_clk_en_i(1'b1), 
                                    .wr_en_i(fifo_we), 
                                    .wr_data_i(i_din), 
                                    .wr_addr_i(fifo_waddr[8:0]), 
                                    .rd_addr_i(fifo_raddr[8:0]), 
                                    .rd_data_o(fifo_dout)) ; 
                    end
    endgenerate
    // Tx side }}}
    // Rx side {{{
    reg [15:0] rx_period_cnt ; 
    reg [3:0] rx_bit_cnt ; // 0: IDLE, 1: Start, 2~9: bit0~7, A:Stop
    reg rx_bit_tick ; 
    reg rx_sample_tick ; 
    reg [1:0] rxd_lat ; 
    reg [7:0] rxd_shift ; 
    reg rx_valid_tg ; 
    reg [1:0] rx_valid_tg_clk ; 
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rxd_lat <=  2'b0 ;
            else
                rxd_lat <=  {rxd_lat[0],
                        i_rxd} ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rxd_shift <=  8'b0 ;
            else
                if (rx_sample_tick) 
                    rxd_shift <=  {rxd_lat[0],
                            rxd_shift[7:1]} ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rx_valid_tg <=  1'b0 ;
            else
                if ((rx_sample_tick & (rx_bit_cnt == 4'hA))) 
                    rx_valid_tg <=  (!rx_valid_tg) ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                o_dout <=  8'b0 ;
            else
                if ((rx_sample_tick & (rx_bit_cnt == 4'hA))) 
                    o_dout <=  rxd_shift ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rx_bit_cnt <=  4'b0 ;
            else
                if (((rx_bit_cnt == 4'b0) && (rxd_lat == 2'b10))) 
                    rx_bit_cnt <=  4'd1 ;
                else
                    if (((rx_bit_cnt == 4'hA) && rx_bit_tick)) 
                        rx_bit_cnt <=  4'd0 ;
                    else
                        if (((rx_bit_cnt != 4'b0) && rx_bit_tick)) 
                            rx_bit_cnt <=  (rx_bit_cnt + 4'd1) ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rx_period_cnt <=  16'b0 ;
            else
                if ((rx_bit_cnt == 4'b0)) 
                    rx_period_cnt <=  16'b0 ;
                else
                    if ((rx_period_cnt == 16'b0)) 
                        rx_period_cnt <=  r_period ;
                    else
                        rx_period_cnt <=  (rx_period_cnt - 16'd1) ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rx_bit_tick <=  1'b0 ;
            else
                if ((rx_period_cnt == 16'd1)) 
                    rx_bit_tick <=  1'b1 ;
                else
                    rx_bit_tick <=  1'b0 ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rx_sample_tick <=  1'b0 ;
            else
                if ((rx_period_cnt == {1'b0,
                        r_period[15:1]})) 
                    rx_sample_tick <=  1'b1 ;
                else
                    rx_sample_tick <=  1'b0 ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                rx_valid_tg_clk <=  2'b0 ;
            else
                rx_valid_tg_clk <=  {rx_valid_tg_clk[0],
                        rx_valid_tg} ;
        end
    always
        @(posedge clk)
        begin
            if ((resetn == 1'b0)) 
                o_valid <=  1'b0 ;
            else
                o_valid <=  (rx_valid_tg_clk[0] != rx_valid_tg_clk[1]) ;
        end

// Rx side }}}
endmodule


