/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.5
    2025 08 06 07:36:59
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ahbl_uart (clk, i_rxd, o_txd, int_o, ahbl_haddr_i, ahbl_hburst_i,
    ahbl_hprot_i, ahbl_hrdata_o, ahbl_hsize_i, ahbl_htrans_i, ahbl_hwdata_i,
    ahbl_hmastlock_i, ahbl_hready_i, ahbl_hreadyout_o, ahbl_hsel_i,
    ahbl_hwrite_i, resetn, ahbl_hresp_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  i_rxd;
    output  o_txd;
    output  int_o;
    input  [31:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    input  [3:0]  ahbl_hprot_i;
    output  [31:0]  ahbl_hrdata_o;
    input  [2:0]  ahbl_hsize_i;
    input  [1:0]  ahbl_htrans_i;
    input  [31:0]  ahbl_hwdata_i;
    input  ahbl_hmastlock_i;
    input  ahbl_hready_i;
    output  ahbl_hreadyout_o;
    input  ahbl_hsel_i;
    input  ahbl_hwrite_i;
    input  resetn;
    output  ahbl_hresp_o;
endmodule