/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.5
    2025 08 02 17:29:21
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module gpio0 (gpi_o, gpo_o, int_o, ahbl_haddr_i, ahbl_hburst_i, ahbl_hrdata_o,
    ahbl_hsize_i, ahbl_htrans_i, ahbl_hwdata_i, ahbl_hclk_i, ahbl_hresetn_i,
    ahbl_hready_i, ahbl_hreadyout_o, ahbl_hresp_o, ahbl_hsel_i, ahbl_hwrite_i,
    gpio_io)/* synthesis syn_black_box syn_declare_black_box=1 */;
    output  [7:0]  gpi_o;
    output  [7:0]  gpo_o;
    output  int_o;
    input  [31:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    output  [31:0]  ahbl_hrdata_o;
    input  [2:0]  ahbl_hsize_i;
    input  [1:0]  ahbl_htrans_i;
    input  [31:0]  ahbl_hwdata_i;
    input  ahbl_hclk_i;
    input  ahbl_hresetn_i;
    input  ahbl_hready_i;
    output  ahbl_hreadyout_o;
    output  ahbl_hresp_o;
    input  ahbl_hsel_i;
    input  ahbl_hwrite_i;
    inout  [7:0]  gpio_io;
endmodule