/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.t.105.0
    Soft IP Version: 1.0.1
    2025 08 07 13:55:20
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module gpll (ref_clk_i, rst_n_i, lock_o, outcore_o, outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  lock_o;
    output  outcore_o;
    output  outglobal_o;
endmodule