/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.1.0.2506031608
    Soft IP Version: 1.0.9
    2025 08 13 22:38:30
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module i2cm (int_o, htrans_i, hsel_i, hwrite_i, haddr_i, hwdata_i, hready_i,
    hburst_i, hsize_i, hrdata_o, hresp_o, hready_o, clk_i, resetn_i, scl_io,
    sda_io)/* synthesis syn_black_box syn_declare_black_box=1 */;
    output  int_o;
    input  [1:0]  htrans_i;
    input  hsel_i;
    input  hwrite_i;
    input  [31:0]  haddr_i;
    input  [31:0]  hwdata_i;
    input  hready_i;
    input  [2:0]  hburst_i;
    input  [2:0]  hsize_i;
    output  [31:0]  hrdata_o;
    output  hresp_o;
    output  hready_o;
    input  clk_i;
    input  resetn_i;
    inout  scl_io;
    inout  sda_io;
endmodule